version: '3.9'

services:
  my_app:
    build:
      context: ./
      dockerfile: ./Dockerfile2

    expose:
      - '4000'
    deploy:
      replicas: 4

    restart: always

    environment:
      - PING_LISTEN_PORT=4000

    networks:
      - front-network

    volumes:
      - db_data:/app/bdd.db

  proxy:
    image: nginx:latest

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
      - 9090:80

    depends_on:
      - my_app

    networks:
      - front-network

networks:
  front-network:
    driver: bridge
volumes:
  db_data:
